### ISSUE TITLE
Ubuntu 22.04 Wireshark -> Lua:Error during loading 

### ISSUE THREAD

**Issue by Nuradioconcepts** [telekom/OpenAPI-Dissector#2]
Ubuntu 22.04 
Lua 5.2.4

I have gotten this to work on my mac but have had issues installing on Ubuntu. I copy all the .lua files to the Personal Lua Plugins directory - /root/.local/lib/wireshark/plugins, but when I reopen wireshark I receive the following error. 

I have tried this as root and as standard user and get the same error. 

Lua: Error during loading:
/root/.local/lib/wireshark/plugins/openapi_spec.lua:3: module 'rex_pcre2' not found:
	no field package.preload['rex_pcre2']
	no file '/root/.local/lib/wireshark/plugins/rex_pcre2.lua'
	no file '/root/.local/lib/wireshark/plugins/rex_pcre2.lua'
	no file '/usr/lib/x86_64-linux-gnu/wireshark/plugins/rex_pcre2.lua'
	no file '/root/.local/lib/wireshark/plugins/rex_pcre2.lua'
	no file '/root/.local/lib/wireshark/plugins/rex_pcre2.lua'
	no file '/usr/lib/x86_64-linux-gnu/wireshark/plugins/rex_pcre2.lua'
	no file '/root/.local/lib/wireshark/plugins/rex_pcre2.lua'
	no file '/root/.local/lib/wireshark/plugins/rex_pcre2.lua'
	no file '/usr/lib/x86_64-linux-gnu/wireshark/plugins/rex_pcre2.lua'
	no file '/root/.local/lib/wireshark/plugins/rex_pcre2.lua'
	no file '/root/.local/lib/wireshark/plugins/rex_pcre2.lua'
	no file '/usr/lib/x86_64-linux-gnu/wireshark/plugins/rex_pcre2.lua'
	no file '/usr/local/share/lua/5.2/rex_pcre2.lua'
	no file '/usr/local/share/lua/5.2/rex_pcre2/init.lua'
	no file '/usr/local/lib/lua/5.2/rex_pcre2.lua'
	no file '/usr/local/lib/lua/5.2/rex_pcre2/init.lua'
	no file '/usr/share/lua/5.2/rex_pcre2.lua'
	no file '/usr/share/lua/5.2/rex_pcre2/init.lua'
	no file './rex_pcre2.lua'
	no file '/usr/local/lib/lua/5.2/rex_pcre2.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/rex_pcre2.so'
	no file '/usr/lib/lua/5.2/rex_pcre2.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './rex_pcre2.so'
stack traceback:
	[C]: in function 'require'
	/root/.local/lib/wireshark/plugins/openapi_spec.lua:3: in main chunk
	[C]: in function 'require'
	/root/.local/lib/wireshark/plugins/openapi.lua:3: in main chunk

**Comment by lukas2511** [comment]
I'm not entirely sure why exactly, but it seems that at least under Ubuntu the library needs to be explicitly installed: `apt install lua-rex-pcre2`

I'll add that to the README in a small troubleshooting section. Thanks for reporting!

**Comment by Nuradioconcepts** [comment]
Great, thank you I will try this out.

I had tried various other methods of installing rex_pcre2 but was not finding anything specific to the .lua file it was referencing in the error.

From: Lukas Schauer ***@***.***>
Date: Friday, April 12, 2024 at 5:25 AM
To: telekom/OpenAPI-Dissector ***@***.***>
Cc: Ryan Decker ***@***.***>, Author ***@***.***>
Subject: Re: [telekom/OpenAPI-Dissector] Ubuntu 22.04 Wireshark -> Lua:Error during loading (Issue #2)

I'm not entirely sure why exactly, but it seems that at least under Ubuntu the library needs to be explicitly installed: apt install lua-rex-pcre2

I'll add that to the README in a small troubleshooting section. Thanks for reporting!
